puts "The students of Villains Academy"
puts "---------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Kruger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
